# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guru-SP
author: ''
email: contato@gurusp.org
description: >- # this means to ignore newlines until "baseurl:"
   O Grupo de Usuários Ruby de São Paulo é uma associação de pessoas interessadas em aprender, ensinar e divulgar o uso da linguagem de programação Ruby e de outros assuntos relacionados ao desenvolvimento de software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gurusp.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guru_sp
github_username:  guru-sp
youtube_username: GuruSPtalks
meetup_username: Guru-SP-Grupo-de-Usuarios-Ruby-de-Sao-Paulo
meetup_title: Meetup
facebook_group_username: gurusp
facebook_group_title: Grupo no Facebook
google_groups_username: ruby-sp
google_groups_title: Lista de discussão
list_title: Encontros
lang: pt-BR
header_logo_url: assets/images/gurusp-2018-site.svg
web_logo_url: assets/images/guru_sp_web_logo.svg


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  encontros:
    output: true
    permalink: /:collection/:slug

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
